/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.BitcoinD.BitcoinDir;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javafx.scene.chart.XYChart;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Sid
 */
public class BitcoinMChartJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BitcoinMChartJPanel
     */
    private JPanel processContainer;
    private BitcoinDir bitcoinDir;
    public BitcoinMChartJPanel(JPanel processContainer, BitcoinDir bitcoinDir) {
        initComponents();
        this.processContainer= processContainer;
        
        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
      
      
     //  barChartData.setValue(7003   ,  "Price","1");
       barChartData.setValue( 6844  ,  "Price","2");
   //    barChartData.setValue(  7102 ,  "Price","3");
       barChartData.setValue(  7456 ,  "Price","4");
       
  //      barChartData.setValue(7937,  "Price","5");
        barChartData.setValue(  6815 ,  "Price","6");
  //      barChartData.setValue( 6630  ,  "Price","7");
        barChartData.setValue(  6919 ,  "Price","8");
  //      barChartData.setValue( 7044  ,  "Price","9");
       barChartData.setValue(6773,  "Price","10");
       
    //   barChartData.setValue( 6843  ,  "Price","11");
       barChartData.setValue(  6955 ,  "Price","12");
  //     barChartData.setValue( 7901  ,  "Price","13");
       barChartData.setValue(  7874 ,  "Price","14");
   //    barChartData.setValue(8357,  "Price","15");
       barChartData.setValue(  8337 ,  "Price","16");
   //    barChartData.setValue(  8071 ,  "Price","17");
       barChartData.setValue(  7944 ,  "Price","18");
    //   barChartData.setValue( 8159  ,  "Price","19");
       barChartData.setValue(8916,  "Price","20");
   //    barChartData.setValue( 8848  ,  "Price","21");
       barChartData.setValue( 8925  ,  "Price","22");
   //    barChartData.setValue( 8794  ,  "Price","23");
       barChartData.setValue( 8934  ,  "Price","24");
       
   //    barChartData.setValue(9652,  "Price","25");
        barChartData.setValue(  8905 ,  "Price","26");
       
         

        JFreeChart barChart = ChartFactory.createBarChart("April", "Day", "Price", barChartData, PlotOrientation.VERTICAL, false, true, false);

        CategoryPlot barchrt = barChart.getCategoryPlot();

        barchrt.setRangeGridlinePaint(Color.ORANGE);

        ChartPanel barPanel = new ChartPanel(barChart);
        barPanel.setBounds(0, 0, 500, 500);
        pane.add(barPanel);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Bitcoin Monthly Price");

        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        processContainer.remove(this);
        CardLayout layout = (CardLayout) processContainer.getLayout();
        layout.previous(processContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pane;
    // End of variables declaration//GEN-END:variables
}
